# Pandas Idioms
So what are these? Idioms may be reffered as short hand techniques to write python programs. We will see what we mean soon enough. __Pandorable__ is a term famous in the pandas community for codes apply Python Idioms to its full extend and usage.

Lets see a few examples of pandas idioms.

In [1]:
#Lets first import our data processing libraries
import numpy as np
import pandas as pd

In [2]:
#Lets now import the dataset we are going to work with.
dataset=pd.read_csv("assets/census.csv")
dataset.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

Let do 1 thing in 2 different ways. Our task here is simply print only those rows where SUMLEV is equal to 50 while converting STNAME and CTYNAME as indexes and renaming column STNAME as State Name.

In [3]:
#Lets do the pandorable way of doing this.
dataset1=dataset.where(dataset["SUMLEV"]==50).rename(columns={"STNAME":"STATE NAME"}).set_index(["STATE NAME","CTYNAME"]).dropna()
dataset1.head()

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STATE NAME CTYNAME
Alabama    Autauga County    50.0     3.0       6.0    1.0     1.0
           Baldwin County    50.0     3.0       6.0    1.0     3.0
           Barbour County    50.0     3.0       6.0    1.0     5.0
           Bibb County       50.0     3.0       6.0    1.0     7.0
           Blount County     50.0     3.0       6.0    1.0     9.0

                           CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STATE NAME CTYNAME
Alabama    Autauga County        54571.0            54571.0          54660.0
           Baldwin County       182265.0           182265.0         183193.0
           Barbour County        27457.0            27457.0          27341.0
           Bibb County           22915.0            22919.0          22861.0
           Blount County         57322.0            57322.0          57373.0

                           POPESTIMATE2011  POPESTIMATE2012  ...  \
STATE NAME CTYNAME                                           ...
Alabama    Autauga County          55253.0          55175.0  ...
           Baldwin County         186659.0         190396.0  ...
           Barbour County          27226.0          27159.0  ...
           Bibb County             22733.0          22642.0  ...
           Blount County           57711.0          57776.0  ...

                           RDOMESTICMIG2011  RDOMESTICMIG2012  \
STATE NAME CTYNAME
Alabama    Autauga County          7.242091         -2.915927
           Baldwin County         14.832960         17.647293
           Barbour County         -4.728132         -2.500690
           Bibb County            -5.527043         -5.068871
           Blount County           1.807375         -1.177622

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STATE NAME CTYNAME
Alabama    Autauga County         -3.012349          2.265971
           Baldwin County         21.845705         19.243287
           Barbour County         -7.056824         -3.904217
           Bibb County            -6.201001         -0.177537
           Blount County          -1.748766         -2.062535

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STATE NAME CTYNAME
Alabama    Autauga County         -2.530799     7.606016    -2.626146
           Baldwin County         17.197872    15.844176    18.559627
           Barbour County        -10.543299    -4.874741    -2.758113
           Bibb County             0.177258    -5.088389    -4.363636
           Blount County          -1.369970     1.859511    -0.848580

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STATE NAME CTYNAME
Alabama    Autauga County    -2.722002     2.592270    -2.187333
           Baldwin County    22.727626    20.317142    18.293499
           Barbour County    -7.167664    -3.978583   -10.543299
           Bibb County       -5.403729     0.754533     1.107861
           Blount County     -1.402476    -1.577232    -0.884411

[5 rows x 98 columns]

In [4]:
#Lets now do the not so pandorable way of solving this questions
dataset2=dataset.where(dataset["SUMLEV"]==50)
dataset2=dataset2.rename(columns={"STNAME":"STATE NAME"})
dataset2=dataset2.set_index(["STATE NAME","CTYNAME"])
dataset2=dataset2.dropna()
dataset2.head()

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STATE NAME CTYNAME
Alabama    Autauga County    50.0     3.0       6.0    1.0     1.0
           Baldwin County    50.0     3.0       6.0    1.0     3.0
           Barbour County    50.0     3.0       6.0    1.0     5.0
           Bibb County       50.0     3.0       6.0    1.0     7.0
           Blount County     50.0     3.0       6.0    1.0     9.0

                           CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STATE NAME CTYNAME
Alabama    Autauga County        54571.0            54571.0          54660.0
           Baldwin County       182265.0           182265.0         183193.0
           Barbour County        27457.0            27457.0          27341.0
           Bibb County           22915.0            22919.0          22861.0
           Blount County         57322.0            57322.0          57373.0

                           POPESTIMATE2011  POPESTIMATE2012  ...  \
STATE NAME CTYNAME                                           ...
Alabama    Autauga County          55253.0          55175.0  ...
           Baldwin County         186659.0         190396.0  ...
           Barbour County          27226.0          27159.0  ...
           Bibb County             22733.0          22642.0  ...
           Blount County           57711.0          57776.0  ...

                           RDOMESTICMIG2011  RDOMESTICMIG2012  \
STATE NAME CTYNAME
Alabama    Autauga County          7.242091         -2.915927
           Baldwin County         14.832960         17.647293
           Barbour County         -4.728132         -2.500690
           Bibb County            -5.527043         -5.068871
           Blount County           1.807375         -1.177622

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STATE NAME CTYNAME
Alabama    Autauga County         -3.012349          2.265971
           Baldwin County         21.845705         19.243287
           Barbour County         -7.056824         -3.904217
           Bibb County            -6.201001         -0.177537
           Blount County          -1.748766         -2.062535

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STATE NAME CTYNAME
Alabama    Autauga County         -2.530799     7.606016    -2.626146
           Baldwin County         17.197872    15.844176    18.559627
           Barbour County        -10.543299    -4.874741    -2.758113
           Bibb County             0.177258    -5.088389    -4.363636
           Blount County          -1.369970     1.859511    -0.848580

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STATE NAME CTYNAME
Alabama    Autauga County    -2.722002     2.592270    -2.187333
           Baldwin County    22.727626    20.317142    18.293499
           Barbour County    -7.167664    -3.978583   -10.543299
           Bibb County       -5.403729     0.754533     1.107861
           Blount County     -1.402476    -1.577232    -0.884411

[5 rows x 98 columns]

Lets now observe what amount of time the two codes takes.

In [5]:
#For measuring time we will use the timeit library
import timeit

Lets see the syntax of using timeit attribute of timeit library
###### timeit.timeit(< Function  Whose Work Of Time is to be measured >, number=< Number of time task is to be repeated and find average >)

In [6]:
#Method 1 time calculation
def first_approach():
    global df
    # And we'll just paste our code right here
    return (df.where(df['SUMLEV']==50)
             .dropna()
             .set_index(['STNAME','CTYNAME'])
             .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))

# Read in our dataset anew
df = pd.read_csv('assets/census.csv')

# And now lets run it
timeit.timeit(first_approach, number=10)

0.3081544999999988

In [7]:
#Method 2 time calculation
def second_approach():
    global df
    new_df = df[df['SUMLEV']==50]
    new_df.set_index(['STNAME','CTYNAME'], inplace=True)
    return new_df.rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'})

# Read in our dataset anew
df = pd.read_csv('assets/census.csv')

# And now lets run it
timeit.timeit(second_approach, number=10)

0.0906015

As observable, though the First approach is more pandorable, the second approach is faster, but note that this may not always be the case.

Lets give you some lecture and revisionism on previously learned concepts. Lets talk about __map__.
The general syntax is,
###### map(<  Function Name >,< Iterable >)
As observable above, the parameters passed are iterable such as lists, tuples,etc and a function name which generally signifies the function in which the iterable is passed. This function then works on each and every element of the iterable, and gives us iterable itself but a changed one.

In dataframes there is method called __applymap__. It takes dataframe name as one of its parameter and name of function through which dataframe is to be passed as another parameter. The general syntax of usage is
###### applymap(< Function Name >, < Dataframe Name >)
This method operates on each and every cell of dataframe a returns an output.

Another option is the __apply__ method. It provides us the option of operating over rows and columns in place of operating over each and every cell. It alse takes 2 parameter, first being the function name, and second being the axis. The general syntax of usage is,
###### < DataFrame >.apply(< Function >, axis=)
Lets see a few examples and understand.


###### Lets do this, lets find the max population estimates for the years 2010,2011,2012,2013,2014,2015

In [8]:
def max_min(dataFrame):
    selectedColumns=dataFrame[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    return pd.Series({"max":np.max(selectedColumns),"min":np.min(selectedColumns)})

In [9]:
popDataSet=pd.read_csv("assets/census.csv")
popDataSet.apply(max_min,axis="columns").head()

       max      min
0  4858979  4785161
1    55347    54660
2   203709   183193
3    27341    26489
4    22861    22512

Well here we returned a series only. Well in place of doing that lets do one thing that we should return a dataframe instead but the max and min columns must added to it.

In [10]:
def max_min_2(dataFrame):
    selectedColumns=dataFrame[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    dataFrame["Max"]=np.max(selectedColumns)
    dataFrame["Min"]=np.min(selectedColumns)
    return(dataFrame)

In [11]:
#Lets call the function
popDataSet.apply(max_min_2,axis="columns").head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,Max,Min
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,4858979,4785161
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,55347,54660
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,203709,183193
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,27341,26489
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,22861,22512

Lets move a step ahead and discuss about lambas. Again another revisionism here.

The general syntax of using lambas is as follow
###### < Variable >=lamba x: < Any Operation With x >
As examplar expression is of lambda is

__lambda x:x*2__

This expression doubles any number that is being passed through x.

Lambdas primarily create ad-hoc functions without requiring the default/orthodox function declaration methodology. 

We now are going to discuss casses where we are going to use lambda functions for data manipulation along with map.

Lets see a few examples.


I believe that the map and apply functions work the same manner. Why?

Both of these functions take two parameters, one being the function on which futher operations are to be carried and second parameter is an iterable. For previous example, we saw we passed a list as the iterable in the map function.

But for apply we pass axis.

Lets deep dive into axis and understand how do they work.

axis stores either row or columns. axis generally tells the interpreter to how to iterate over a set a data. If we pass columns as axis it will iterate over a row, column wise.

Similarly if we pass row as axis value we will find that we get iterations over rows to rows in a common column.

In [27]:
#Lets do what we did in previous question but this time using lambda functions.
rows = ['POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013','POPESTIMATE2014', 
        'POPESTIMATE2015']
popDataSet.apply(lambda x:np.max(x[rows]),axis=1).head()

0    4858979
1      55347
2     203709
3      27341
4      22861
dtype: int64

###### Let's say we want to divide the states into four categories: Northeast, Midwest, South, and West We can write a customized function that returns the region based on the state the state regions information is obtained from Wikipedia.

In [28]:
def get_state_region(x):
    northeast = ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 
                 'Rhode Island','Vermont','New York','New Jersey','Pennsylvania']
    midwest = ['Illinois','Indiana','Michigan','Ohio','Wisconsin','Iowa',
               'Kansas','Minnesota','Missouri','Nebraska','North Dakota',
               'South Dakota']
    south = ['Delaware','Florida','Georgia','Maryland','North Carolina',
             'South Carolina','Virginia','District of Columbia','West Virginia',
             'Alabama','Kentucky','Mississippi','Tennessee','Arkansas',
             'Louisiana','Oklahoma','Texas']
    west = ['Arizona','Colorado','Idaho','Montana','Nevada','New Mexico','Utah',
            'Wyoming','Alaska','California','Hawaii','Oregon','Washington']
    
    if x in northeast:
        return "Northeast"
    elif x in midwest:
        return "Midwest"
    elif x in south:
        return "South"
    else:
        return "West"

In [29]:
# Now we have the customized function, let's say we want to create a new column called Region, which shows the
# state's region, we can use the customized function and the apply function to do so. The customized function
# is supposed to work on the state name column STNAME. So we will set the apply function on the state name
# column and pass the customized function into the apply function
df['state_region'] = df['STNAME'].apply(lambda x: get_state_region(x))

In [30]:
# Now let's see the results
df[['STNAME','state_region']].head()

    STNAME state_region
0  Alabama        South
1  Alabama        South
2  Alabama        South
3  Alabama        South
4  Alabama        South